//Answer 1
SELECT DEPARTMENT_ID, LISTAGG(FIRST_NAME || ' ' || LAST_NAME,',')
WITHIN GROUP (ORDER BY DEPARTMENT_ID) RESULT
FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID;

//Answer 2
SELECT HR.EMPLOYEES.*, SUM(SALARY) OVER
(PARTITION BY JOB_ID ORDER BY EMPLOYEE_ID ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)
NUM FROM HR.EMPLOYEES;

//Answer 3
SELECT EMPLOYEE_ID,PHONE_NUMBER,HIRE_DATE,DEPARTMENT_ID, LEAD(PHONE_NUMBER,1) OVER
(PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE) NEXT
FROM HR.EMPLOYEES;

//Answer 4
SELECT EMPLOYEES.*,RANK() OVER (ORDER BY SALARY DESC,HIRE_DATE ASC) SALARY_RANK
FROM HR.EMPLOYEES
ORDER BY SALARY_RANK;

//Answer 5
SELECT EMPLOYEE_ID, NTILE(4) OVER (ORDER BY EMPLOYEE_ID)
FROM HR.EMPLOYEES;

//Answer 6
SELECT EMPLOYEE_ID , SALARY , DEPARTMENT_ID,
CASE
    WHEN SALARY<avg_salary_lower THEN 0
    ELSE 1
    END AS SALARY_LABEL
FROM (SELECT EMPLOYEE_ID , SALARY , DEPARTMENT_ID,
AVG(SALARY) OVER (PARTITION BY DEPARTMENT_ID) AS avg_salary_lower FROM HR.EMPLOYEES)
ORDER BY 1,3;

//Answer 7
SELECT e.EMPLOYEE_ID, e.HIRE_DATE, e.DEPARTMENT_ID FROM HR.EMPLOYEES E
JOIN(
    SELECT EMPLOYEE_ID,HIRE_DATE
    FROM ( SELECT EMPLOYEE_ID,HIRE_DATE,
    ROW_NUMBER() OVER (PARTITION BY EXTRACT(YEAR FROM hıre_date) ORDER BY hire_date) AS Ranked
    FROM HR.EMPLOYEES) RANKED_EMPLOYEES
    WHERE RANKED = 1
    ) first_employee_per_year
    ON e.EMPLOYEE_ID = first_employee_per_year.EMPLOYEE_ID
    AND e.hire_date = first_employee_per_year.HIRE_DATE;
    
//Answer 8
SELECT * FROM HR.EMPLOYEES WHERE EMPLOYEE_ID NOT IN (
SELECT EMPLOYEE_ID FROM (
SELECT EMPLOYEE_ID, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID
ORDER BY SALARY DESC) SALARY_RANK
FROM HR.EMPLOYEES) RANKED
WHERE SALARY_RANK=1);


//Answer 9
SELECT * FROM HR.EMPLOYEES WHERE EMPLOYEE_ID NOT IN (
SELECT EMPLOYEE_ID FROM (
SELECT EMPLOYEE_ID, DENSE_RANK() OVER (PARTITION BY DEPARTMENT_ID
ORDER BY SALARY DESC) SALARY_RANK
FROM HR.EMPLOYEES )RANKED
WHERE SALARY_RANK>2);


//Answer10
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME FULL_NAME, E.DEPARTMENT_ID,
E.HIRE_DATE, DENSE_RANK() OVER( PARTITION BY DEPARTMENT_ID ORDER BY HIRE_DATE) AS RANK
FROM HR.EMPLOYEES E ORDER BY DEPARTMENT_ID, HIRE_DATE;
